### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by clefru** [mikedeboer/jsDAV#110]
"npm install jsDAV" gives you a release that's over a year old. Please update.

(I have been bitten by https://github.com/mikedeboer/jsDAV/issues/79, which I could have avoided by having a newer version.)

Thanks!

**Comment by aetna-softwares** [comment]
I also run into an already fixed bug (#82) and only after debugging for half a day and ready to send a patch, I see that it was fixed for over a year :(

please do a npm release

thanks!

**Comment by mikedeboer** [comment]
ah, yes, my apologies!

**Comment by aetna-softwares** [comment]
thanks !!
