### ISSUE TITLE
Calling back with a Exc.NeedPrivileges from beforeBind still allows the file to be created

### ISSUE THREAD

**Issue by vramdal** [mikedeboer/jsDAV#114]
I'm writing an authorization plugin, based on jsDAV/lib/DAVACL/plugin.js. In the `beforeBind` method, I'm calling `this.checkPrivileges(parentPath, "{DAV:}bind", null, e.next.bind(e))`, which calls back with `return callback(new Exc.NeedPrivileges(uri, privileges), false);` if the user cannot create the file.

However, the file is created nonetheless. In `jsDAV/lib/DAV/handler.js`, the method `createFile` only checks if the argument to its callback method is `=== true`. This seems wrong, as the authentication plugin returns an exception (which is obviously not `=== true`). I suggest also checking if the argument is `!= undefined`, in which case it should be an error:

    this.createFile = function(uri, dataOrStream, enc, cbcreatefile) {
        var parts = Util.splitPath(uri);
        var dir   = parts[0];
        var name  = parts[1];
        var self  = this;

        this.dispatchEvent("beforeBind", uri, function(stop, etag) {
            if (stop === true) 
                return cbcreatefile(null, etag);
            if (stop) // This will return if stop is != undefined
                return self.handleError(stop);
            self.getNodeForPath(dir, function(err, parent) {

**Comment by mikedeboer** [comment]
That was a big gaping hole... thanks for filing the ticket!!
