### ISSUE TITLE
dispatchEvent with multiple arguments in the callback

### ISSUE THREAD

**Issue by mnutt** [mikedeboer/jsDAV#133]
I noticed in `lib/DAV/handler.js` in `createFile()` it does: 

```
self.dispatchEvent("beforeCreateFile", uri, dataOrStream, enc, parent, function(stop, etag) {
```

This looks like it was added in https://github.com/mikedeboer/jsDAV/commit/d9a1005f02a7124e0548045f143c924f9902e9e3 for parity with the way other functions pass an etag. But is it possible to actually pass an etag back as a second argument in my `beforeCreateFile` handler? Or if not, is there a workaround for it?

Right now I'm just not calling `e.next()` at all from my listener and just finishing the request myself, but it means I have to disable the listener timeouts which seems ugly.

**Comment by mikedeboer** [comment]
Sorry for the late reply! I think you should be able to pass back an etag - just like the other `beforeCreateFile` handlers do. Please check the linked commit :wink:
