### ISSUE TITLE
VObject/Property .hasFeature is not defined on String

### ISSUE THREAD

**Issue by joernroeder** [mikedeboer/jsDAV#141]
i've just read througth the VObject code and saw this `if else` statement in the `property.add` function: https://github.com/mikedeboer/jsDAV/blob/master/lib/VObject/property.js#L224 You're handling the difference between a `Node object` and a `string` here but `string` doesn't have a `.hasFeature` method.
Therefore i suggest to switch the statement.
What do you think? I can submit a pull request if you like :)

```
if(typeof item == "string") {
}
else if (item.hasFeature(jsVObject_Parameter)) {
}
```

**Comment by joernroeder** [comment]
I've also found a similar switch in https://github.com/mikedeboer/jsDAV/blob/master/lib/VObject/component.js#L166 which does the same thing but doesn't break anything due to the additional `if (item.hasFeature && …)` check.

**Comment by mikedeboer** [comment]
Yeah, that looks good - please submit a pull request!

**Comment by joernroeder** [comment]
jup, i'll clean up my repo, squash my commits and open a pull request.
